/**
 * This class is generated by jOOQ
 */
package be.soldier.money.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabelRecord extends org.jooq.impl.UpdatableRecordImpl<be.soldier.money.persistence.jooq.tables.records.LabelRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Byte, java.lang.Byte, java.lang.Double, java.lang.Integer> {

	private static final long serialVersionUID = -2143675079;

	/**
	 * Setter for <code>money.label.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>money.label.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>money.label.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>money.label.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>money.label.type</code>.
	 */
	public void setType(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>money.label.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>money.label.year</code>.
	 */
	public void setYear(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>money.label.year</code>.
	 */
	public java.lang.Integer getYear() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>money.label.fixed</code>.
	 */
	public void setFixed(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>money.label.fixed</code>.
	 */
	public java.lang.Byte getFixed() {
		return (java.lang.Byte) getValue(4);
	}

	/**
	 * Setter for <code>money.label.income</code>.
	 */
	public void setIncome(java.lang.Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>money.label.income</code>.
	 */
	public java.lang.Byte getIncome() {
		return (java.lang.Byte) getValue(5);
	}

	/**
	 * Setter for <code>money.label.default_amount</code>.
	 */
	public void setDefaultAmount(java.lang.Double value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>money.label.default_amount</code>.
	 */
	public java.lang.Double getDefaultAmount() {
		return (java.lang.Double) getValue(6);
	}

	/**
	 * Setter for <code>money.label.default_recipient_id</code>.
	 */
	public void setDefaultRecipientId(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>money.label.default_recipient_id</code>.
	 */
	public java.lang.Integer getDefaultRecipientId() {
		return (java.lang.Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Byte, java.lang.Byte, java.lang.Double, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Byte, java.lang.Byte, java.lang.Double, java.lang.Integer> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return be.soldier.money.persistence.jooq.tables.Label.LABEL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return be.soldier.money.persistence.jooq.tables.Label.LABEL.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return be.soldier.money.persistence.jooq.tables.Label.LABEL.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return be.soldier.money.persistence.jooq.tables.Label.LABEL.YEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return be.soldier.money.persistence.jooq.tables.Label.LABEL.FIXED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field6() {
		return be.soldier.money.persistence.jooq.tables.Label.LABEL.INCOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field7() {
		return be.soldier.money.persistence.jooq.tables.Label.LABEL.DEFAULT_AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return be.soldier.money.persistence.jooq.tables.Label.LABEL.DEFAULT_RECIPIENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getYear();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getFixed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value6() {
		return getIncome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value7() {
		return getDefaultAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getDefaultRecipientId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value3(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value4(java.lang.Integer value) {
		setYear(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value5(java.lang.Byte value) {
		setFixed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value6(java.lang.Byte value) {
		setIncome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value7(java.lang.Double value) {
		setDefaultAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord value8(java.lang.Integer value) {
		setDefaultRecipientId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LabelRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4, java.lang.Byte value5, java.lang.Byte value6, java.lang.Double value7, java.lang.Integer value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LabelRecord
	 */
	public LabelRecord() {
		super(be.soldier.money.persistence.jooq.tables.Label.LABEL);
	}

	/**
	 * Create a detached, initialised LabelRecord
	 */
	public LabelRecord(java.lang.Integer id, java.lang.String name, java.lang.String type, java.lang.Integer year, java.lang.Byte fixed, java.lang.Byte income, java.lang.Double defaultAmount, java.lang.Integer defaultRecipientId) {
		super(be.soldier.money.persistence.jooq.tables.Label.LABEL);

		setValue(0, id);
		setValue(1, name);
		setValue(2, type);
		setValue(3, year);
		setValue(4, fixed);
		setValue(5, income);
		setValue(6, defaultAmount);
		setValue(7, defaultRecipientId);
	}
}
