/**
 * This class is generated by jOOQ
 */
package be.soldier.money.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TxRecord extends org.jooq.impl.UpdatableRecordImpl<be.soldier.money.persistence.jooq.tables.records.TxRecord> implements org.jooq.Record10<java.lang.Integer, java.lang.String, java.sql.Date, java.lang.Double, java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Date, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 978818646;

	/**
	 * Setter for <code>money.tx.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>money.tx.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>money.tx.reference</code>.
	 */
	public void setReference(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>money.tx.reference</code>.
	 */
	public java.lang.String getReference() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>money.tx.date</code>.
	 */
	public void setDate(java.sql.Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>money.tx.date</code>.
	 */
	public java.sql.Date getDate() {
		return (java.sql.Date) getValue(2);
	}

	/**
	 * Setter for <code>money.tx.amount</code>.
	 */
	public void setAmount(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>money.tx.amount</code>.
	 */
	public java.lang.Double getAmount() {
		return (java.lang.Double) getValue(3);
	}

	/**
	 * Setter for <code>money.tx.from_account_id</code>.
	 */
	public void setFromAccountId(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>money.tx.from_account_id</code>.
	 */
	public java.lang.Integer getFromAccountId() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>money.tx.recipient_id</code>.
	 */
	public void setRecipientId(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>money.tx.recipient_id</code>.
	 */
	public java.lang.Integer getRecipientId() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>money.tx.communication</code>.
	 */
	public void setCommunication(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>money.tx.communication</code>.
	 */
	public java.lang.String getCommunication() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>money.tx.date_compta</code>.
	 */
	public void setDateCompta(java.sql.Date value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>money.tx.date_compta</code>.
	 */
	public java.sql.Date getDateCompta() {
		return (java.sql.Date) getValue(7);
	}

	/**
	 * Setter for <code>money.tx.label_id</code>.
	 */
	public void setLabelId(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>money.tx.label_id</code>.
	 */
	public java.lang.Integer getLabelId() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>money.tx.label_index</code>.
	 */
	public void setLabelIndex(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>money.tx.label_index</code>.
	 */
	public java.lang.Integer getLabelIndex() {
		return (java.lang.Integer) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.sql.Date, java.lang.Double, java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Date, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.sql.Date, java.lang.Double, java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Date, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return be.soldier.money.persistence.jooq.tables.Tx.TX.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return be.soldier.money.persistence.jooq.tables.Tx.TX.REFERENCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field3() {
		return be.soldier.money.persistence.jooq.tables.Tx.TX.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field4() {
		return be.soldier.money.persistence.jooq.tables.Tx.TX.AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return be.soldier.money.persistence.jooq.tables.Tx.TX.FROM_ACCOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return be.soldier.money.persistence.jooq.tables.Tx.TX.RECIPIENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return be.soldier.money.persistence.jooq.tables.Tx.TX.COMMUNICATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field8() {
		return be.soldier.money.persistence.jooq.tables.Tx.TX.DATE_COMPTA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return be.soldier.money.persistence.jooq.tables.Tx.TX.LABEL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return be.soldier.money.persistence.jooq.tables.Tx.TX.LABEL_INDEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getReference();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value3() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value4() {
		return getAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getFromAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getRecipientId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getCommunication();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value8() {
		return getDateCompta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getLabelId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getLabelIndex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxRecord value2(java.lang.String value) {
		setReference(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxRecord value3(java.sql.Date value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxRecord value4(java.lang.Double value) {
		setAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxRecord value5(java.lang.Integer value) {
		setFromAccountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxRecord value6(java.lang.Integer value) {
		setRecipientId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxRecord value7(java.lang.String value) {
		setCommunication(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxRecord value8(java.sql.Date value) {
		setDateCompta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxRecord value9(java.lang.Integer value) {
		setLabelId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxRecord value10(java.lang.Integer value) {
		setLabelIndex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxRecord values(java.lang.Integer value1, java.lang.String value2, java.sql.Date value3, java.lang.Double value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.String value7, java.sql.Date value8, java.lang.Integer value9, java.lang.Integer value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TxRecord
	 */
	public TxRecord() {
		super(be.soldier.money.persistence.jooq.tables.Tx.TX);
	}

	/**
	 * Create a detached, initialised TxRecord
	 */
	public TxRecord(java.lang.Integer id, java.lang.String reference, java.sql.Date date, java.lang.Double amount, java.lang.Integer fromAccountId, java.lang.Integer recipientId, java.lang.String communication, java.sql.Date dateCompta, java.lang.Integer labelId, java.lang.Integer labelIndex) {
		super(be.soldier.money.persistence.jooq.tables.Tx.TX);

		setValue(0, id);
		setValue(1, reference);
		setValue(2, date);
		setValue(3, amount);
		setValue(4, fromAccountId);
		setValue(5, recipientId);
		setValue(6, communication);
		setValue(7, dateCompta);
		setValue(8, labelId);
		setValue(9, labelIndex);
	}
}
