/**
 * This class is generated by jOOQ
 */
package be.soldier.money.persistence.jooq;

/**
 * Convenience access to all tables in money
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table money.account
	 */
	public static final be.soldier.money.persistence.jooq.tables.Account ACCOUNT = be.soldier.money.persistence.jooq.tables.Account.ACCOUNT;

	/**
	 * The table money.label
	 */
	public static final be.soldier.money.persistence.jooq.tables.Label LABEL = be.soldier.money.persistence.jooq.tables.Label.LABEL;

	/**
	 * The table money.notes
	 */
	public static final be.soldier.money.persistence.jooq.tables.Notes NOTES = be.soldier.money.persistence.jooq.tables.Notes.NOTES;

	/**
	 * The table money.tx
	 */
	public static final be.soldier.money.persistence.jooq.tables.Tx TX = be.soldier.money.persistence.jooq.tables.Tx.TX;
}
