/**
 * This class is generated by jOOQ
 */
package be.soldier.money.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account extends org.jooq.impl.TableImpl<be.soldier.money.persistence.jooq.tables.records.AccountRecord> {

	private static final long serialVersionUID = 64116680;

	/**
	 * The reference instance of <code>money.account</code>
	 */
	public static final be.soldier.money.persistence.jooq.tables.Account ACCOUNT = new be.soldier.money.persistence.jooq.tables.Account();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.soldier.money.persistence.jooq.tables.records.AccountRecord> getRecordType() {
		return be.soldier.money.persistence.jooq.tables.records.AccountRecord.class;
	}

	/**
	 * The column <code>money.account.id</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.AccountRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>money.account.name</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.AccountRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>money.account.account_number</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.AccountRecord, java.lang.String> ACCOUNT_NUMBER = createField("account_number", org.jooq.impl.SQLDataType.VARCHAR.length(19).nullable(false), this, "");

	/**
	 * The column <code>money.account.own</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.AccountRecord, java.lang.Byte> OWN = createField("own", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>money.account</code> table reference
	 */
	public Account() {
		this("account", null);
	}

	/**
	 * Create an aliased <code>money.account</code> table reference
	 */
	public Account(java.lang.String alias) {
		this(alias, be.soldier.money.persistence.jooq.tables.Account.ACCOUNT);
	}

	private Account(java.lang.String alias, org.jooq.Table<be.soldier.money.persistence.jooq.tables.records.AccountRecord> aliased) {
		this(alias, aliased, null);
	}

	private Account(java.lang.String alias, org.jooq.Table<be.soldier.money.persistence.jooq.tables.records.AccountRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.soldier.money.persistence.jooq.Money.MONEY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<be.soldier.money.persistence.jooq.tables.records.AccountRecord, java.lang.Integer> getIdentity() {
		return be.soldier.money.persistence.jooq.Keys.IDENTITY_ACCOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.soldier.money.persistence.jooq.tables.records.AccountRecord> getPrimaryKey() {
		return be.soldier.money.persistence.jooq.Keys.KEY_ACCOUNT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.soldier.money.persistence.jooq.tables.records.AccountRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.soldier.money.persistence.jooq.tables.records.AccountRecord>>asList(be.soldier.money.persistence.jooq.Keys.KEY_ACCOUNT_PRIMARY, be.soldier.money.persistence.jooq.Keys.KEY_ACCOUNT_ACCOUNT_NUMBER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.soldier.money.persistence.jooq.tables.Account as(java.lang.String alias) {
		return new be.soldier.money.persistence.jooq.tables.Account(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.soldier.money.persistence.jooq.tables.Account rename(java.lang.String name) {
		return new be.soldier.money.persistence.jooq.tables.Account(name, null);
	}
}
