/**
 * This class is generated by jOOQ
 */
package be.soldier.money.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Label extends org.jooq.impl.TableImpl<be.soldier.money.persistence.jooq.tables.records.LabelRecord> {

	private static final long serialVersionUID = 1873943523;

	/**
	 * The reference instance of <code>money.label</code>
	 */
	public static final be.soldier.money.persistence.jooq.tables.Label LABEL = new be.soldier.money.persistence.jooq.tables.Label();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.soldier.money.persistence.jooq.tables.records.LabelRecord> getRecordType() {
		return be.soldier.money.persistence.jooq.tables.records.LabelRecord.class;
	}

	/**
	 * The column <code>money.label.id</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.LabelRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>money.label.name</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.LabelRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>money.label.type</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.LabelRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>money.label.year</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.LabelRecord, java.lang.Integer> YEAR = createField("year", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>money.label.fixed</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.LabelRecord, java.lang.Byte> FIXED = createField("fixed", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * The column <code>money.label.income</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.LabelRecord, java.lang.Byte> INCOME = createField("income", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * The column <code>money.label.default_amount</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.LabelRecord, java.lang.Double> DEFAULT_AMOUNT = createField("default_amount", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>money.label.default_recipient_id</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.LabelRecord, java.lang.Integer> DEFAULT_RECIPIENT_ID = createField("default_recipient_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>money.label</code> table reference
	 */
	public Label() {
		this("label", null);
	}

	/**
	 * Create an aliased <code>money.label</code> table reference
	 */
	public Label(java.lang.String alias) {
		this(alias, be.soldier.money.persistence.jooq.tables.Label.LABEL);
	}

	private Label(java.lang.String alias, org.jooq.Table<be.soldier.money.persistence.jooq.tables.records.LabelRecord> aliased) {
		this(alias, aliased, null);
	}

	private Label(java.lang.String alias, org.jooq.Table<be.soldier.money.persistence.jooq.tables.records.LabelRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.soldier.money.persistence.jooq.Money.MONEY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<be.soldier.money.persistence.jooq.tables.records.LabelRecord, java.lang.Integer> getIdentity() {
		return be.soldier.money.persistence.jooq.Keys.IDENTITY_LABEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.soldier.money.persistence.jooq.tables.records.LabelRecord> getPrimaryKey() {
		return be.soldier.money.persistence.jooq.Keys.KEY_LABEL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.soldier.money.persistence.jooq.tables.records.LabelRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.soldier.money.persistence.jooq.tables.records.LabelRecord>>asList(be.soldier.money.persistence.jooq.Keys.KEY_LABEL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<be.soldier.money.persistence.jooq.tables.records.LabelRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<be.soldier.money.persistence.jooq.tables.records.LabelRecord, ?>>asList(be.soldier.money.persistence.jooq.Keys.LABEL_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.soldier.money.persistence.jooq.tables.Label as(java.lang.String alias) {
		return new be.soldier.money.persistence.jooq.tables.Label(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.soldier.money.persistence.jooq.tables.Label rename(java.lang.String name) {
		return new be.soldier.money.persistence.jooq.tables.Label(name, null);
	}
}
