/**
 * This class is generated by jOOQ
 */
package be.soldier.money.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notes extends org.jooq.impl.TableImpl<be.soldier.money.persistence.jooq.tables.records.NotesRecord> {

	private static final long serialVersionUID = 132658120;

	/**
	 * The reference instance of <code>money.notes</code>
	 */
	public static final be.soldier.money.persistence.jooq.tables.Notes NOTES = new be.soldier.money.persistence.jooq.tables.Notes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.soldier.money.persistence.jooq.tables.records.NotesRecord> getRecordType() {
		return be.soldier.money.persistence.jooq.tables.records.NotesRecord.class;
	}

	/**
	 * The column <code>money.notes.id</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.NotesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>money.notes.content</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.NotesRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>money.notes</code> table reference
	 */
	public Notes() {
		this("notes", null);
	}

	/**
	 * Create an aliased <code>money.notes</code> table reference
	 */
	public Notes(java.lang.String alias) {
		this(alias, be.soldier.money.persistence.jooq.tables.Notes.NOTES);
	}

	private Notes(java.lang.String alias, org.jooq.Table<be.soldier.money.persistence.jooq.tables.records.NotesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Notes(java.lang.String alias, org.jooq.Table<be.soldier.money.persistence.jooq.tables.records.NotesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.soldier.money.persistence.jooq.Money.MONEY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<be.soldier.money.persistence.jooq.tables.records.NotesRecord, java.lang.Integer> getIdentity() {
		return be.soldier.money.persistence.jooq.Keys.IDENTITY_NOTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.soldier.money.persistence.jooq.tables.records.NotesRecord> getPrimaryKey() {
		return be.soldier.money.persistence.jooq.Keys.KEY_NOTES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.soldier.money.persistence.jooq.tables.records.NotesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.soldier.money.persistence.jooq.tables.records.NotesRecord>>asList(be.soldier.money.persistence.jooq.Keys.KEY_NOTES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.soldier.money.persistence.jooq.tables.Notes as(java.lang.String alias) {
		return new be.soldier.money.persistence.jooq.tables.Notes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.soldier.money.persistence.jooq.tables.Notes rename(java.lang.String name) {
		return new be.soldier.money.persistence.jooq.tables.Notes(name, null);
	}
}
