/**
 * This class is generated by jOOQ
 */
package be.soldier.money.persistence.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Money extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1499598990;

	/**
	 * The reference instance of <code>money</code>
	 */
	public static final Money MONEY = new Money();

	/**
	 * No further instances allowed
	 */
	private Money() {
		super("money");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			be.soldier.money.persistence.jooq.tables.Account.ACCOUNT,
			be.soldier.money.persistence.jooq.tables.Label.LABEL,
			be.soldier.money.persistence.jooq.tables.Notes.NOTES,
			be.soldier.money.persistence.jooq.tables.Tx.TX);
	}
}
