/**
 * This class is generated by jOOQ
 */
package be.soldier.money.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tx extends org.jooq.impl.TableImpl<be.soldier.money.persistence.jooq.tables.records.TxRecord> {

	private static final long serialVersionUID = -174166150;

	/**
	 * The reference instance of <code>money.tx</code>
	 */
	public static final be.soldier.money.persistence.jooq.tables.Tx TX = new be.soldier.money.persistence.jooq.tables.Tx();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<be.soldier.money.persistence.jooq.tables.records.TxRecord> getRecordType() {
		return be.soldier.money.persistence.jooq.tables.records.TxRecord.class;
	}

	/**
	 * The column <code>money.tx.id</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.TxRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>money.tx.reference</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.TxRecord, java.lang.String> REFERENCE = createField("reference", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>money.tx.date</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.TxRecord, java.sql.Date> DATE = createField("date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>money.tx.amount</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.TxRecord, java.lang.Double> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

	/**
	 * The column <code>money.tx.from_account_id</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.TxRecord, java.lang.Integer> FROM_ACCOUNT_ID = createField("from_account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>money.tx.recipient_id</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.TxRecord, java.lang.Integer> RECIPIENT_ID = createField("recipient_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>money.tx.communication</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.TxRecord, java.lang.String> COMMUNICATION = createField("communication", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>money.tx.date_compta</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.TxRecord, java.sql.Date> DATE_COMPTA = createField("date_compta", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>money.tx.label_id</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.TxRecord, java.lang.Integer> LABEL_ID = createField("label_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>money.tx.label_index</code>.
	 */
	public final org.jooq.TableField<be.soldier.money.persistence.jooq.tables.records.TxRecord, java.lang.Integer> LABEL_INDEX = createField("label_index", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>money.tx</code> table reference
	 */
	public Tx() {
		this("tx", null);
	}

	/**
	 * Create an aliased <code>money.tx</code> table reference
	 */
	public Tx(java.lang.String alias) {
		this(alias, be.soldier.money.persistence.jooq.tables.Tx.TX);
	}

	private Tx(java.lang.String alias, org.jooq.Table<be.soldier.money.persistence.jooq.tables.records.TxRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tx(java.lang.String alias, org.jooq.Table<be.soldier.money.persistence.jooq.tables.records.TxRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, be.soldier.money.persistence.jooq.Money.MONEY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<be.soldier.money.persistence.jooq.tables.records.TxRecord, java.lang.Integer> getIdentity() {
		return be.soldier.money.persistence.jooq.Keys.IDENTITY_TX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<be.soldier.money.persistence.jooq.tables.records.TxRecord> getPrimaryKey() {
		return be.soldier.money.persistence.jooq.Keys.KEY_TX_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<be.soldier.money.persistence.jooq.tables.records.TxRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<be.soldier.money.persistence.jooq.tables.records.TxRecord>>asList(be.soldier.money.persistence.jooq.Keys.KEY_TX_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<be.soldier.money.persistence.jooq.tables.records.TxRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<be.soldier.money.persistence.jooq.tables.records.TxRecord, ?>>asList(be.soldier.money.persistence.jooq.Keys.TX_IBFK_1, be.soldier.money.persistence.jooq.Keys.TX_IBFK_2, be.soldier.money.persistence.jooq.Keys.TX_IBFK_3);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public be.soldier.money.persistence.jooq.tables.Tx as(java.lang.String alias) {
		return new be.soldier.money.persistence.jooq.tables.Tx(alias, this);
	}

	/**
	 * Rename this table
	 */
	public be.soldier.money.persistence.jooq.tables.Tx rename(java.lang.String name) {
		return new be.soldier.money.persistence.jooq.tables.Tx(name, null);
	}
}
